### PR TITLE
Rest mappings

### PR DESCRIPTION
**Pull request by BluewaterSolutions**
Implement REST Mappings for Lucee

### CODE REVIEW

**Comment by BluewaterSolutions** [comment]
this is completely fubar...

**Comment by bdw429s** [comment]
The conflict is probably a commit I added today. Just rebase your branch with the upstream master to incorporate the changes.

**Comment by bdw429s** [comment]
I've never understood why, but every time I make any change to `BaseConfig.cfc`, it always shows every line in the file changed.  If I add `?w=1` to the URL on the diff it says there are "only whitespace changes" there.

**Comment by elpete** [comment]
I fixed a few files like that in our application templates using a `mac2unix` command line tool. I’ll submit a PR. 

Any other files do that?

**Comment by bdw429s** [comment]
That's the only file on this repo that does it.

**Comment by jcberquist** [comment]
@elpete: thanks! When I was submitting my recent pull requests I noticed that `BaseConfig.cfc` had  Windows line endings `\r\n` and it caused issues for me until I changed my `autocrlf` settings.

**Comment by BluewaterSolutions** [comment]
@elpete to the rescue. Thanks!

**Comment by elpete** [comment]
Pull open here: https://github.com/Ortus-Solutions/cfconfig/pull/8

**Comment by bdw429s** [comment]
@elpete @BluewaterSolutions I just merged in Eric's pull.  I hope it doesn't screw up your pull too bad.  Try and rebase to the new master branch.  Let me know when you think this pull is ready to merge.  I'm mostly waiting right now because you were going to look into Adobe's implementation.  I'm ok doing several pulls to get it in pieces if you like.  I just don't like keeping pulls around for the same issues we're having right now is the moving target of the upstream :)

**Comment by BluewaterSolutions** [comment]
i agree, this last request came automatically(i think) because i pushed changes using @elpete fix. ACF is next on my list.

**Comment by bdw429s** [comment]
@BluewaterSolutions rebase your branch against the current master branch of the main repo and then fix that conflict if it's still there.  Then let me know if I should merge what you have thus far.

**Comment by BluewaterSolutions** [comment]
OK, that looks much better. Back to ACF implementation.

**Comment by bdw429s** [comment]
I'm going to close this for now.  Can you open a new pull if you ever finish this?

**Pull request closed without merging**
