### PR TITLE
Feature/cfconfig 20 add railo exporting capabilities

### PR DESCRIPTION
**Pull request by cybersonic**
As per the ticket https://ortussolutions.atlassian.net/browse/CFCONFIG-20 , Here is a first pass at implementing the Railo Server and Web providers.

### CODE REVIEW

**Comment by bdw429s** [comment]
Awesome work and thx for the tests!  :)

**Comment by bdw429s** [comment]
@cybersonic Hey, quick question-- how much did you need to change between Lucee and Railo for this to work.  If the Railo one is nearly identical to Lucee, what do you think about trying to share the same base class between them and overriding the few places where it's different?  I'm just thinking if they're 99% the same, every Lucee change I make make will also basically need added to Railo as well.

**Comment by cybersonic** [comment]
Looking at the diff's, so far it;s basically the same except for a few instances of `cfLuceeConfiguration` vs `cfRailoConfiguration` 

I didn't know this at the start so I guess we can refactor it out too. Maybe we can mark it for refactoring rather than stopping the feature? I shall add a ticket.

**Comment by bdw429s** [comment]
Well, this pull is already merged so nothing is 'stopped' :)  It was just an idea.  If we can just make every instance of "lucee|railo" be a variable then that might be a good refactor to reduce the code duplication.

**Pull request merged**
