### PR TITLE
Cfml event gateways

### PR DESCRIPTION
**Pull request by bferdinandus**
Added event gateway support for all adobe versions

### CODE REVIEW

**Comment by bferdinandus** [comment]
@bdw429s I updated the pullrequest.

**Comment by bdw429s** [comment]
@bferdinandus Thx, I merged this request so we don't bog down the process, but there are a few additional steps to fully support event gateways, would you like to submit a pull for that as well:

* Add any new complex config itesm to the array around line 238 of `CFConfigService` so the `diff()` function properly nests the config items when doing diffs. (this repo) 
https://github.com/Ortus-Solutions/cfconfig/blob/master/models/CFConfigService.cfc#L238-L248
* Add the same items to the `if()` statement around line 210 of the `cfconfig diff` command so the output of that command properly nests config items.  (This is in the commandbox-cfconfig repo for the CLI portion)
https://github.com/Ortus-Solutions/commandbox-cfconfig/blob/master/commands/cfconfig/diff.cfc#L210-L218
* Add a new namespace (possibly two) to the `cfconfig` commands to allow addition of event gateways and their configs from the CLI.  Look at one of the existing ones for datasources, or scheduled tasks.  It's mostly boilerplate and just swapping out all the correct param names.  (This is in the commandbox-cfconfig repo for the CLI portion)
https://github.com/Ortus-Solutions/commandbox-cfconfig/tree/master/commands/cfconfig/task

Since we have two new complex config items (config and instances) we can do one of the following:

```
cfconfig eventgatewayconfig save
cfconfig eventgatewayconfig delete
cfconfig eventgatewayconfig list

cfconfig eventgatewayinstance save
cfconfig eventgatewayinstance delete
cfconfig eventgatewayinstance list
```
OR we could nest it deeper like this
```
cfconfig eventgateway config save
cfconfig eventgateway config delete
cfconfig eventgateway config list

cfconfig eventgateway instance save
cfconfig eventgateway instance delete
cfconfig eventgateway instance list
```
Not sure the difference is that big as far as what the user types other than the fact that namespaces are more idiomatic to CommandBox than say this (even though I'm tempted to go with this next option...)

```
cfconfig eventgateway-config save
cfconfig eventgateway-config delete
cfconfig eventgateway-config list

cfconfig eventgateway-instance save
cfconfig eventgateway-instance delete
cfconfig eventgateway-instance list
```
Let me know what you think.  I don't like the readability of option one but it almost feels like the nested namespace serves no purpose in option two other than grouping related commands.  Option three is more readable, but I don't care to hyphenate commands when a namespace will accomplish the same organization.

**Comment by bferdinandus** [comment]
Hi @bdw429s , 
Thanks for helping me complete this feature. I'll add the changes you requested.
To keep the commandbox 'feeling' I would like to go with option one: `cfconfig eventgatewayinstance list`

**Comment by bdw429s** [comment]
Sounds great. I look forward to your next pull :)

**Pull request merged**
