### PR TITLE
Support Lucee system output and error stream config

### PR DESCRIPTION
**Pull request by jcberquist**

### CODE REVIEW

**Comment by bdw429s** [comment]
@jcberquist Can we change this to two config items `systemOut` and `systemErr`?  I'd like to avoid a complex config item as those require the additional `cfconfig XXX list/save/delete` commands to management, and since these items are necessarily related as part of a great config like a datasource configuration or mail server.  Being simple values will let the `cfconfig set` command work directly on them more easily.

**Comment by jcberquist** [comment]
Thanks for the feedback, I was wondering about that. I can change it up.

**Comment by jcberquist** [comment]
The other question I had is how to keep this setting out of Lucee Web config files - I don't think it applies there, is that correct? What I had done is not write anything to the file if the `system` property was not set, now I have two settings and a `system` XML node will get written to config file with no XMLAttributes if those settings are missing (i.e. in a Web config file). Should I do a check to make sure at least one of the two properties is set before writing an `system` XML node to the XML?

**Comment by jcberquist** [comment]
I forced push a change - for now at least I have added a check for either property being set in the config before writing a `system` node to the XML.

**Comment by bdw429s** [comment]
@jcberquist Just add empty `readSystem()` and `writeSystem()` methods to the lucee4web and lucee5wb CFCs.  That will effectively do nothing when interacting with a web context.  Lucee does a good job of ignoring extra config, but that's the correct -- to just use the subclassing to override behaviors.

**Comment by jcberquist** [comment]
Alright, that is done, and seems to be work correctly.

**Comment by bdw429s** [comment]
Awesome, thanks for making the changes @jcberquist !

**Comment by bdw429s** [comment]
CFConfig services bumped and published as `v1.5.8`

**Pull request merged**
