### PR TITLE
Cfconfig 26

### PR DESCRIPTION
**Pull request by bferdinandus**
Added support for MS SQL setting "sendStringParametersAsUnicode"

### CODE REVIEW

**Comment by bdw429s** [comment]
Thanks @bferdinandus I just got back from CFCamp in Germany so taking a look at this now.  What CF engines and DB servers did you test this on?

**Comment by bferdinandus** [comment]
Hi @bdw429s ,

In the Adobe resource files I added a MSSQL datasource.
In the Lucee resource files I added a few datasources like MSSQL, PostgreSQL and Sybase

With Adobe CF2018 and MSSQL I did a check to see if the characters as unicode function was really activated. 
With Adobe CF2016, 11, 10, and lucee 5 and 4 I used the unittests and checked to see if the output file generated by writeConfig was the same as the testfile read by the readConfig function.

**Comment by bdw429s** [comment]
Thanks @bferdinandus , it all seems in order from your tests, I'll give this a merge and try it out on my end as well. Thanks for taking the time to address this.

**Comment by bdw429s** [comment]
@bferdinandus I'm giving this a test today and seeing some behaviors I'm not sure are correct.  If I manually add a datasource via the CLI and don't specify a unicode flag at all:
```
cfconfig datasource save name=test4 dbdriver=MSSQL host=locahost database=myDB
```
then the placeholders are left in the JDBC URL:
```
"dsn":"jdbc:macromedia:sqlserver://locahost;databaseName=myDB;SelectMethod=direct;sendStringParametersAsUnicode={sendStringParametersAsUnicode};querytimeout={queryTimeout};MaxPooledStatements={maxPooledStatements}",
```
You'll note optional placeholders such as `{port}` have logic to remove them if there is no port specified.  This also applies to `queryTimeout`  and `maxPooledStatements`.

Also, the default JDBC URL for Oracle doesn't appear to have the placeholders in it.

Adding a new Oracle datasource like this
```
cfconfig datasource save name=test8 dbdriver=oracle host=locahost database=myDB sendStringParametersAsUnicode=true
```
doesn't actually save the setting
```
"dsn":"jdbc:macromedia:oracle://locahost;AuthenticationMethod=userIDPassword;sendStringParametersAsUnicode=false;querytimeout=0;MaxPooledStatements=100",
```

And finally, can you help explain what this code here is doing:
https://github.com/Ortus-Solutions/cfconfig/pull/27/files#diff-91d3a0983341e4c7c916077a1c6891e4R1302
Since we're tracking those items separately as first class config items and injecting them directly into the JDBC URL, we don't also need them in the custom string I would think.  I thought custom was only for additional JDBC URL bits that the users wanted to add on top of the stuff already configurable out of the box.

**Comment by bferdinandus** [comment]
Thanks for the feedback. I'll have a look why settings are not saved correctly.

**Comment by bferdinandus** [comment]
I have created a pullrequest which  solves the problems with the placeholders for Adobe Datasources. 
I'll try to take a look at the lucee datasources tomorrow.

**Comment by bferdinandus** [comment]
As explanation for this code: https://github.com/Ortus-Solutions/cfconfig/pull/27/files#diff-91d3a0983341e4c7c916077a1c6891e4R1302

I was trying to keep all the parameters in the custom string the same, except for the separately tracked ones, those should override the value in the custom string. In the Lucee config, the only place where the `sendStringParametersAsUnicode` for mssql was saved in the custom string.

I'll refactor it to see if that can be a bit simpler.

**Pull request merged**
