### PR TITLE
Clear out XML loggers array before writing out loggers

### PR DESCRIPTION
**Pull request by jcberquist**

### CODE REVIEW

**Comment by bdw429s** [comment]
Thanks @jcberquist!  Sorry for the delay, I got caught up in Ortus Developer Week.  I was demoing CFConfig and saw all the new logger info in there.  Pretty cool.

**Comment by jcberquist** [comment]
Hey @bdw429s, I am glad that it worked 😄  - one last question about this - I created a top level key of `loggers` for this, I guess because each XML entry is a `<logger/>`, but in Lucee the parent is actually `<logging/>`. Do you care about that? I am indifferent, but if you want it changed I suppose now is the time.

**Comment by bdw429s** [comment]
@jcberquist The name is fine.  Can you check out the diff command and corresponding method in the config service?  There is some special treatment for the top level complex config items like caches, datasources, etc to make sure they compare correctly.  I noticed in my demo that the logger information wasn't nesting correctly in the `cfconfig diff` command output due to that.  You need to add the top level loggers name to an array on line 214 of the CFConfigService in the cfconfig project as well as the if statement around line 150 in the diff command in the commandbox project.

The service will recurse into complex values and mark the top level keys as different if any of the nested keys are different.  Also, all nested items are hidden in the console output of the command unless you're enabled `verbose` output.

**Comment by jcberquist** [comment]
Ah, sorry about that. I haven't really used the diff command so I wasn't aware there was an issue there. I have tried it now and I see what you are talking about.

**Comment by bdw429s** [comment]
Perfect thanks!

**Pull request merged**
